resources:
  - url: http://127.0.0.1:9999/directions-card.js
    type: module
views:
  - cards:
      - type: custom:directions-card
        name: Boilerplate Card Development
        entity: sun.sun
        test_gui: true
